/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.provaindsimulador;

import com.sun.corba.se.impl.orbutil.CorbaResourceUtil;

/**
 *
 * @author Bandtec
 */
public class SimuladorCalculo extends javax.swing.JFrame {

    /**
     * Creates new form SimuladorCalculo
     */
    public SimuladorCalculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeCliente = new javax.swing.JLabel();
        BoxPotenciaLamp = new javax.swing.JTextField();
        lblQuantLamp = new javax.swing.JLabel();
        BoxnomeCliente1 = new javax.swing.JTextField();
        lblPotencLamp = new javax.swing.JLabel();
        BoxQuantLamp = new javax.swing.JTextField();
        lblFuncHora = new javax.swing.JLabel();
        BoxFuncHora = new javax.swing.JTextField();
        lblMetros = new javax.swing.JLabel();
        BoxMetros = new javax.swing.JTextField();
        BtnCalcular = new javax.swing.JToggleButton();
        lblFrase = new javax.swing.JLabel();
        lblFrase2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 650));

        lblNomeCliente.setText("Nome do cliente");

        BoxPotenciaLamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxPotenciaLampActionPerformed(evt);
            }
        });

        lblQuantLamp.setText("Quantidade de lâmpadas");

        BoxnomeCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxnomeCliente1ActionPerformed(evt);
            }
        });

        lblPotencLamp.setText("Potência das lâmpadas");

        BoxQuantLamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxQuantLampActionPerformed(evt);
            }
        });

        lblFuncHora.setText("Horário de funcionamento");

        BoxFuncHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxFuncHoraActionPerformed(evt);
            }
        });

        lblMetros.setText("Metros");

        BoxMetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxMetrosActionPerformed(evt);
            }
        });

        BtnCalcular.setText("Calcular");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        lblFrase.setText("******************************************");

        lblFrase2.setText("******************************************");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFrase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BoxMetros, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMetros)
                            .addComponent(BoxFuncHora, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFuncHora)
                            .addComponent(BoxQuantLamp, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPotencLamp)
                            .addComponent(BoxnomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantLamp)
                            .addComponent(BoxPotenciaLamp, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblNomeCliente))
                            .addComponent(BtnCalcular))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblFrase2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblNomeCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxnomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblQuantLamp)
                .addGap(18, 18, 18)
                .addComponent(BoxQuantLamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblPotencLamp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxPotenciaLamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFuncHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxFuncHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMetros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxMetros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BtnCalcular)
                .addGap(18, 18, 18)
                .addComponent(lblFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFrase2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxPotenciaLampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxPotenciaLampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxPotenciaLampActionPerformed

    private void BoxnomeCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxnomeCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxnomeCliente1ActionPerformed

    private void BoxQuantLampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxQuantLampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxQuantLampActionPerformed

    private void BoxFuncHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxFuncHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxFuncHoraActionPerformed

    private void BoxMetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxMetrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxMetrosActionPerformed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
        // Calculando watts e desconto emputido 
        Integer horaFunc = Integer.parseInt(BoxFuncHora.getText());
        Integer watts = Integer.parseInt(BoxQuantLamp.getText());
        // Tubo solar para que a luz tenha contato com o ambiente
        Double valorTubo = 1000.0;
        // Sensor que regulará a iluminosidade ideal do ambiente
        Double valorSensor = 150.0;
      
    
        Double potencia = Double.parseDouble(BoxPotenciaLamp.getText());
        // quantidade de lampadas que a empresa tem x a potencia 
        Double quantidadeXPotencia = watts * potencia;
        Double kWatts = quantidadeXPotencia / 1000;
        // Para saber quanto a empresa gasta enquanto esta em horario de funcionamento
        // Para saber o gasto por dia e mes
        Double calculoDia = kWatts * horaFunc;
        Double calculoMes = calculoDia * 30;
        Double calculoAno = calculoMes * 12;
        // 0.516 preço do kwatts
        Double valorMes = calculoMes * 0.516; 
        Double valorAno = calculoAno * 0.516;
        // Desconto de 40% 
        Double descontoMes = calculoMes * 0.40;
        Double descontoAno = calculoAno * 0.40;
        // Anuidade dentro do desconto
        Double mensalidade = descontoAno * 0.30;
        
        Double investimento = valorTubo +  valorSensor;
        // vai retornar algo como 0,07 porque misturei double e integer e não
        // achei como transformar s2 <3
        Double retorno = investimento/descontoAno;
        
       lblFrase.setText(String.format("A empresa "
               +  BoxnomeCliente1.getText() + " gasta %.2f por mês e %.2f por ano. "
                       + "Com o nosso projeto a empresa irá economizar cerca de "
                       + "%.2f por mes, e %.2f por ano" , valorMes, valorAno ,
                       descontoMes, descontoAno)); 
                       
       lblFrase2.setText(String.format("o investimento será de %.2f esse valor lhe "
               + "trará lucro apartir do %.2f ano, a partir desse ano será cobrada uma anuidade de %.2f" 
                        , investimento ,retorno, mensalidade));
       
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_BtnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladorCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladorCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladorCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladorCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladorCalculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BoxFuncHora;
    private javax.swing.JTextField BoxMetros;
    private javax.swing.JTextField BoxPotenciaLamp;
    private javax.swing.JTextField BoxQuantLamp;
    private javax.swing.JTextField BoxnomeCliente1;
    private javax.swing.JToggleButton BtnCalcular;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblFrase2;
    private javax.swing.JLabel lblFuncHora;
    private javax.swing.JLabel lblMetros;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblPotencLamp;
    private javax.swing.JLabel lblQuantLamp;
    // End of variables declaration//GEN-END:variables
}
